### ISSUE TITLE
how to add none option in dropdown renderAsDropdown

### ISSUE THREAD

**Issue by ShreeSoftech-Rupesh** [webreinvent/laravel-nestable#4]
I am trying to render a dropdown in my code, and the code is working perfectly. However, I need to add a custom option in the dropdown called 'None,' and I want this option to appear in the first position. How can I achieve this using this package?

**Comment by themodernpk** [comment]
@ShreeSoftech-Rupesh you can refer to https://github.com/webreinvent/laravel-nestable?tab=readme-ov-file#using-independent-models
